exports.collections = [
  {
    handle: 'bridal-rivaah',
    title: 'Bridal Rivaah',
    intro: 'Timeless designs for your big day.',
    heroImage: 'https://images.unsplash.com/photo-1520962919659-a9263f1f1c9a?q=80&w=1200&auto=format',
    tags: ['bridal', 'gold', 'diamond'],
  },
  {
    handle: 'modern-minimal',
    title: 'Modern Minimal',
    intro: 'Clean lines and subtle sparkle.',
    heroImage: 'https://images.unsplash.com/photo-1515562141207-1be5b5d7a9e8?q=80&w=1200&auto=format',
    tags: ['daily-wear', 'platinum', 'rose-gold'],
  },
  {
    handle: 'glam-days',
    title: 'GlamDays',
    intro: 'Make every day glamorous.',
    heroImage: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format',
    tags: ['earring', 'necklace'],
  },
  {
    handle: 'signature-series',
    title: 'Signature Series',
    intro: 'Exclusive statement pieces.',
    heroImage: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?q=80&w=1200&auto=format',
    tags: ['limited', 'featured'],
  },
];

exports.products = [
  {
    slug: 'royal-diamond-earrings',
    name: 'Royal Diamond Earrings',
    description: 'Exquisite diamond earrings crafted for your special day.',
    images: [
      'https://images.unsplash.com/photo-1520962919659-a9263f1f1c9a?q=80&w=800&auto=format',
    ],
    type: 'earring',
    material: 'diamond',
    occasion: 'bridal',
    collection: 'bridal-rivaah',
    sku: 'RDE001',
    sizes: [],
    featured: true,
    mostLoved: true,
    newArrival: true,
  },
  {
    slug: 'eternal-rose-gold-ring',
    name: 'Eternal Rose Gold Ring',
    description: 'A symbol of eternal love in rose gold.',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=800&auto=format'],
    type: 'ring',
    material: 'rose-gold',
    occasion: 'bridal',
    collection: 'bridal-rivaah',
    sku: 'EPR002',
    sizes: ['6', '7', '8'],
    featured: true,
    mostLoved: false,
    newArrival: false,
  },
  {
    slug: 'classic-gold-necklace',
    name: 'Classic Gold Necklace',
    description: 'Elegant gold necklace for everyday elegance.',
    images: ['https://images.unsplash.com/photo-1516637090014-cb1ab0d08fc7?q=80&w=800&auto=format'],
    type: 'necklace',
    material: 'gold',
    occasion: 'daily-wear',
    collection: 'glam-days',
    sku: 'CGN003',
    sizes: [],
    featured: true,
    mostLoved: true,
    newArrival: false,
  },
  {
    slug: 'platinum-diamond-necklace',
    name: 'Platinum Diamond Necklace',
    description: 'Luxurious platinum necklace with diamond accents.',
    images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800&auto=format'],
    type: 'necklace',
    material: 'platinum',
    occasion: 'bridal',
    collection: 'signature-series',
    sku: 'PDN011',
    sizes: [],
    featured: true,
    mostLoved: true,
    newArrival: true,
  },
  {
    slug: 'traditional-gold-bangles',
    name: 'Traditional Gold Bangles',
    description: 'Traditional bangles for festive occasions.',
    images: ['https://images.unsplash.com/photo-1512427691650-860f6a1a4aab?q=80&w=800&auto=format'],
    type: 'bangle',
    material: 'gold',
    occasion: 'festive',
    collection: 'signature-series',
    sku: 'TGB004',
    sizes: ['2.4', '2.6', '2.8'],
    featured: false,
    mostLoved: true,
    newArrival: true,
  },
];

exports.stores = [
  {
    name: 'Jewel Elegance - Mumbai Fort',
    city: 'Mumbai',
    address: '12 Fort Street, Mumbai, MH 400001',
    phone: '+91-22-1234-5678',
    hours: 'Mon–Sat 10am–8pm',
    lat: 18.9318,
    lng: 72.8331,
  },
  {
    name: 'Jewel Elegance - Bengaluru MG Road',
    city: 'Bengaluru',
    address: '88 MG Road, Bengaluru, KA 560001',
    phone: '+91-80-2345-6789',
    hours: 'Mon–Sun 10am–9pm',
    lat: 12.9716,
    lng: 77.5946,
  },
  {
    name: 'Jewel Elegance - Delhi Connaught Place',
    city: 'Delhi',
    address: 'B-2, Connaught Place, New Delhi, DL 110001',
    phone: '+91-11-3456-7890',
    hours: 'Mon–Sat 10am–8pm',
    lat: 28.6329,
    lng: 77.2195,
  },
];
